plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-minimal
title: Mystique
google_analytics: [G-D6WFHVW3QB]
cover-img: "Images/image_test.jpg"
thumbnail-img: "Images/autre_image.jpg"
full-width: true